apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}-worker
  labels:
    {{- include "backend.labels" . | nindent 4 }}
    tier: worker
spec:
  type: {{ .Values.worker.service.type }}
  ports:
    - port: {{ .Values.worker.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "backend.selectorLabels" . | nindent 4 }}
    tier: worker
