startServices: "sqs,dynamodb"
extraEnvVars:
  - name: DEFAULT_REGION
    value: "us-east-1"
  - name: DYNAMODB_SHARE_DB
    value: "1"
  - name: EDGE_PORT
    value: "4566"

enableStartupScripts: true

debug: true

startupScriptContent: |
  #!/bin/sh
  awslocal dynamodb create-table --table-name sora-henkan-dev-main-table --attribute-definitions AttributeName=id,AttributeType=S --key-schema AttributeName=id,KeyType=HASH --billing-mode PAY_PER_REQUEST --region us-east-1
  awslocal dynamodb list-tables --region us-east-1
