apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute-minio-api
  namespace: default
spec:
  parentRefs:
    - name: gateway
      namespace: istio-system
      sectionName: minioapi
  rules:
    - backendRefs:
        - name: minio
          port: 9000
          weight: 100
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute-minio-console
  namespace: default
spec:
  parentRefs:
    - name: gateway
      namespace: istio-system
      sectionName: minioconsole
  rules:
    - backendRefs:
        - name: minio
          port: 9090
          weight: 100
