apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute-rabbit-mgmt
  namespace: default
spec:
  parentRefs:
    - name: gateway
      namespace: istio-system
      sectionName: rabbitmgmt
  rules:
    - backendRefs:
        - name: rabbitmq
          port: 15672
          weight: 100
